### ISSUE TITLE
Feature Request: Poll Permissions

### ISSUE THREAD

**Issue by Repiked** [hyperbotauthor/listrawpoll#2]
The poll now currently is set so that everyone can edit each others' poll and delete them at will. They have all the permissions the creator of the poll has. A feature to help resolve this issue is to make the creators the only editors of the poll. This is necessary so that people cannot edit and change someone else's poll as their own. Thank you in advance.

**Comment by hyperbotauthor** [comment]
No they can't. The buttons are shown, you can click on them, but the server refuses to execute the transaction if the poll owner is different from the verified user.

The transactions are executed by this function https://github.com/hyperbotauthor/listrawpoll/blob/dac57bdb909ba658adb85c1cf6ca2d7008ee8138/classes.js#L296 .

You can see how authenticity is checked in places like https://github.com/hyperbotauthor/listrawpoll/blob/dac57bdb909ba658adb85c1cf6ca2d7008ee8138/classes.js#L347 .

**Comment by hyperbotauthor** [comment]
I added popup messages for the cases when the user tries to perform an unathorized edit operation on polls. So I leave the buttons there, let the user click on them and be educated what they are not allowed to do.

Example:

https://github.com/hyperbotauthor/listrawpoll/blob/4095d4c7e52cf2091d334a0434ba9094a3bac846/app.js#L84

**Comment by hyperbotauthor** [comment]
I'm content with the way things are, closing it now
